# .streamlit/config.toml
[theme]
primaryColor = "#73C0EE"             # azul claro (extraído de tus pantallazos)
backgroundColor = "#FFFFFF"          # fondo principal blanco
secondaryBackgroundColor = "#F6F4EF" # paneles suave (crema)
textColor = "#242024"                # gris muy oscuro
font = "sans serif"
